#stage 1
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /app/

COPY . .

RUN dotnet publish -o out

# stage 2
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

COPY --from=build /app/out .

ENTRYPOINT ["dotnet", "SRP.API.dll"]
